[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106a0eb10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b57d1e7d55de7a1ab77123a9191cf4bd/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106a0e7e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b57d1e7d55de7a1ab77123a9191cf4bd/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106a0f410>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b57d1e7d55de7a1ab77123a9191cf4bd/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106a0fb60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b57d1e7d55de7a1ab77123a9191cf4bd/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106a0fdd0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b57d1e7d55de7a1ab77123a9191cf4bd/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105903800>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/b57d1e7d55de7a1ab77123a9191cf4bd/screenshot